name: Update docs

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  pull:
    uses: retejs/.github/.github/workflows/update-docs.yml@main
    secrets: inherit
    with:
      filename: "3.rete-area-3d-plugin"
      package: rete-area-3d-plugin
